### ISSUE TITLE
pod install 

### ISSUE THREAD

**Issue by EmizenIphoneTeam** [sparklit/adbutler-ios-sdk#1]
I am Working on Xcode 9.4.1 and Swift 4.1. But This Pod (pod 'adbutler-ios-sdk', '~> 1.0.2') not install.
Error in coming Unable to find a specification for `adbutler-ios-sdk (~> 1.0.2)` in Terminal

**Comment by wprevett** [comment]
Hello EmizenIphoneTeam, This repo was created a couple of years ago by a developer no longer with our team.  We are currently working on a new swift 4.1 SDK which should be available soon.  In the meantime, try changing your pod name to AdButler (according to the podspec file in this repo, that is the correct name).  It seems the version should be 1.0.1

**Comment by EmizenIphoneTeam** [comment]
when is coming new pod for xcode 10.0 and swift 4.1 ?. Because i urgent needed upadated pod .

**Comment by wprevett** [comment]
Are you unable to use version 1.0.1?

**Comment by EmizenIphoneTeam** [comment]
Yes

**Comment by EmizenIphoneTeam** [comment]
I am already tried this 1.0.1 version.This pod not work.

**Comment by wprevett** [comment]
I downloaded the pod and it seems to work for me.  If you are using swift 4.1 you will need to add this to the ABImageView tap function **@objc** func tap().  if you need more help send me an email.  will@adbutler.com.  We don't have an estimate right now on when the newer SDK will be available.  If it's urgent, give me a shout.
