### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jaredcowoCS** [sparklit/adbutler-ios-sdk#8]
Is this SDK documented?

**Comment by wprevett** [comment]
Everything you need to get ads displaying should be in the Readme file.  There is also a newer SDK version in testing right now you can try if you like [click here](https://github.com/adbutler/adbutler-ios-mraid-sdk)

**Comment by jaredcowoCS** [comment]
Where do I get my accountID? ZoneID?

**Comment by wprevett** [comment]
The easiest way is to look at the URL bar when you're in the AdButler interface

Navigate to your zone and you should see something like this:

admin.adbutler.com/?ID=**XXXXX**&p=zone.view&zoneID=**YYYYY**&tab=0

Where **XXXXX** is your account ID and **YYYYY** is your zone ID
